services:
  cyber-chef:
    restart: no
    container_name: cyberchef
    image: mpepping/cyberchef:latest
    ports:
      - 127.0.0.1:8000:8000
  
  mitmproxy:
    image: mitmproxy/mitmproxy:latest
    container_name: mitmproxy
    volumes:
      - ./mitmproxy:/home/mitmproxy/.mitmproxy # for ca-certs
    ports:
      - 127.0.0.1:8082:8080 # default mitmdump
      - 127.0.0.1:8083:8081 # default mitmweb
    command:
      - mitmweb
      - --web-host
      - 0.0.0.0
      - --ssl-insecure
  
  tor:
    image: peterdavehello/tor-socks-proxy:latest
    container_name: tor
    ports:
      - 127.0.0.1:9050:9150

  pentest:
    container_name: pentest
    build:
      context: .
    restart: no
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.ip_forward=1
    cap_add: 
      - NET_ADMIN
    devices:
      - /dev/net/tun
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - ./transf:/transf # to transfer data
      - ./mitmproxy:/mitmproxy
    ports:
      - 9990-9999:9990-9999 # Misc ports for whatever
    tty: true
    stdin_open: true