services:
  cyber-chef:
    restart: no
    image: mpepping/cyberchef:latest
    ports:
      - 8000:8000
  
  mitmproxy:
    restart: no
    image: mitmproxy/mitmproxy:latest
    volumes:
      - ./mitmproxy:/home/mitmproxy/.mitmproxy 
    ports:
      - 8090:8080 # mapped default
    tty: true
    stdin_open: true
     
  pentest-tools:
    build:
      context: ./build
    restart: no
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.ip_forward=1
    cap_add: 
      - NET_ADMIN
    devices:
      - /dev/net/tun
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - ./transf:/transf # to transfer data
      - ./mitmproxy:/mitmproxy # for ca-certs
    ports:
      - 9990-9999:9990-9999 # Misc ports for whatever