#!/bin/bash
trap "kill 0" SIGINT SIGQUIT

help() {
    cat << EOF

Checks proxy list against target with HEAD request
Usage: proxy_test [opts...] <file>

File format: protocol,proxy,port,username,password
username and password are optional

Options:

  -h    Show this help

  -t    Set connect timeout in seconds.
        Default: 1

  -w    Set target to test against.
        Default: https://www.example.com

  -d    Set delimiter.
        Default: ,

  -j    Set number of parallel jobs.
        Default: 8
  
  -u    Set User-Agent.
        Default: 'Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0'
  
  -k    Ignore tls certificate check on proxy. 
        Usefull if exit node is (tor/i2p/etc).
        Do not use othewise.
        Default: enabled

EOF
exit 0
}

if [ "$#" == 0 ]; then
  help
  exit 1
fi

export timeout=1
export target='https://www.example.com'
export delimiter=','
export n_processes=8
export user_agent='Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0'
export ignore_cert=''

check_proxy() {
  args=($@)
  protocol=${args[0]}
  proxy=${args[1]}
  port=${args[2]}
  if [ ${#args[@]} -eq 5 ]; then
    auth="--proxy-user ${args[3]}:${args[4]}"
  fi
  
  RETURN_CODE=$(curl $auth \
                  $ignore_cert \
                  --silent \
                  --head \
                  --connect-timeout $timeout \
                  --header "User-Agent: ${user_agent}" \
                  --output /dev/null \
                  --write-out "%{http_code}" \
                  --proxy $protocol://$proxy:$port \
                  $target)
  if [ "$RETURN_CODE" -eq 200 ]; then
    echo ${args[@]} | sed "s/ /$delimiter/g"
  fi
}
export -f check_proxy

OPTSTRING="ht:w:d:j:u:k"
while getopts ${OPTSTRING} opt; do
  case ${opt} in
    h)   help ;;
    t)   timeout=${OPTARG} ;;
    w)   target=${OPTARG} ;;
    d)   delimiter=${OPTARG} ;;
    j)   n_processes=${OPTARG} ;;
    u)   user_agent=${OPTARG} ;;
    k)   ignore_cert='--insecure' ;;
    ?)
      echo "Invalid option, use -h to show help"
      exit 1
      ;;
  esac
done
shift $((OPTIND-1))

while IFS= read -r line
do
  while IFS=${delimiter} read -r -a array
  do
    if [ ${#array[@]} -eq 3 ] || \
       [ ${#array[@]} -eq 5 ]
    then
      sem -j ${n_processes} check_proxy ${array[@]}
    else
      echo "${line} - wrong format, use -h to show help"
    fi
  done <<< ${line}
done < $1