#!/bin/sh
PROXY_TYPE=$2
TIMEOUT=$3
check_proxy() {
    local PROXY=$1
    IS_ALIVE=$(echo `curl -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Gecko/20100101 Firefox/130.0" -m $TIMEOUT -f -s -x $PROXY_TYPE://$PROXY http://www.example.com/`)
    if [[ -n $IS_ALIVE  ]]; then
        echo "$PROXY_TYPE $PROXY" | sed 's/:/ /'
    fi
}

LINES=`cat $1`
for LINE in $LINES; do
    check_proxy $LINE &
done
wait